version: '3.8'

services:
  kup:
    container_name: kup
    build: .
    volumes:
      - /home/alexf/.azure:/root/.azure
      - ./out:/kup/out
    environment:
      - AUTHOR_EMAIL=aliaksandr.fedaryna@accuristech.com
      - AUTHOR_TITLE=LEAD II, SOFTWARE DEVELOPMENT/ENGINEERING
      - MANAGER=Yauheni Bulychau
      - MANAGER_TITLE=LEAD III, SOFTWARE DEVELOPMENT/ENGINEERING
    stdin_open: true
    tty: true