version: '3.8'

services:
  kup:
    container_name: kup
    image: fedorinoalex/kup-generator:latest
    volumes:
      - ./out:/kup/out
    environment:
      - AZURE_DEVOPS_EXT_PAT=
      - AUTHOR_EMAIL=aliaksandr.fedaryna@accuristech.com
      - AUTHOR_TITLE=LEAD II, SOFTWARE DEVELOPMENT/ENGINEERING
      - MANAGER=Yauheni Bulychau
      - MANAGER_TITLE=LEAD III, SOFTWARE DEVELOPMENT/ENGINEERING
    stdin_open: true
    tty: true
