version: '3.8'

services:
  kup:
    container_name: kup
    image: fedorinoalex/kup-generator:latest
    volumes:
      - ./out:/kup/out
    environment:
      - AZURE_DEVOPS_EXT_PAT=
      - AUTHOR_EMAIL=your.email@at.domain.com
      - AUTHOR_TITLE=YOUR TITLE, SOFTWARE DEVELOPMENT/ENGINEERING
      - MANAGER=Your Manager
      - MANAGER_TITLE=MANAGERS TITLE
    stdin_open: true
    tty: true
